### ISSUE TITLE
可以支持telnet吗？

### ISSUE THREAD

**Issue by boy6585948** [xin053/switchbackup#1]
可以增加对telnet的支持吗？

**Comment by xin053** [comment]
这个脚本不再做功能变更，因为后来发现了更好用的针对交换机操作的 python 包: [`napalm`](https://github.com/napalm-automation/napalm)，支持主流交换机，支持 ssh 和telnet 等

华为交换机的支持通过如下两个插件实现，使用也比较简单：

1. [`napalm-ce`](https://github.com/napalm-automation-community/napalm-ce)
2. [`napalm-huawei-vrp`](https://github.com/napalm-automation-community/napalm-huawei-vrp)
