### ISSUE TITLE
关于收集交换机其他信息的问题

### ISSUE THREAD

**Issue by hanziqing0630** [xin053/switchbackup#2]
能否实现除了保存配置文件之外，收集一些其他的display信息，比如display cpu-usage？

**Comment by xin053** [comment]
display 信息属于监控需求，可通过 [napalm](https://github.com/napalm-automation/napalm) 解析 display 输出实现。我这边有实现一个获取交换机 cpu 内存 板卡 电源 温度等信息的脚本，后续开源
